### ISSUE TITLE
Broken Subversion link on homepage

### ISSUE THREAD

**Issue by ryandesign** [creytiv/rem#17]
rem's [web page](http://www.creytiv.com/rem.html) says the source can be downloaded from [a subversion repository](https://svn.creytiv.com/rem/trunk) but that server is offline. Perhaps change it to a link to this GitHub repo instead?

See [related issue in re](https://github.com/creytiv/re/issues/115).

**Comment by alfredh** [comment]
Thanks for reporting, I updated the homepage:

http://www.creytiv.com/rem.html

please verify and close issue if ok.

Alfred

**Comment by ryandesign** [comment]
Thanks!
