### ISSUE TITLE
Add struct for audio frame and timestamp?

### ISSUE THREAD

**Issue by alfredh** [creytiv/rem#19]
This is an idea to add a new type for containing an audio frame,
similar to how `struct vidframe` contains a video frame.

Suggested type:

```c
struct auframe {
    enum aufmt fmt;
    void *sampv;
    size_t sampc;
    uint64_t timestamp;  /* microseconds resolution? */
};
```

```c
/** Video frame */
struct vidframe {
	uint8_t *data[4];      /**< Video planes        */
	uint16_t linesize[4];  /**< Array of line-sizes */
	struct vidsz size;     /**< Frame resolution    */
	enum vidfmt fmt;       /**< Video pixel format  */
	uint64_t timestamp;
};
```

I am also wondering if we should add `timestamp` to vidframe.

Many video devices provide the exact time of the video frame. Similar with some
audio cards/drivers, that provides audio samples and also timing info.

**Comment by richaas** [comment]
IMO we should keep timestamp as a separate argument. This information is not necessarily part of the core frame information. For the audio frame, we already have many interfaces defined using int16_t *sampv, size_t sampc format. I don't like the idea of updating all of those. I suggest we experiment with the auframe concept in an application, and reconsider based on experience learnt from that.

**Comment by alfredh** [comment]
okay thanks for the input ..

I also have an ambivalent relationship to the timestamp info. nice to have it in the
struct but strange if you have to set it to a bogus value, if the info is not relevant.

I will experiment with `auframe` in baresip :)
