### ISSUE TITLE
Wrong index is calculated in g711_pcm2alaw

### ISSUE THREAD

**Issue by kbeckmann** [creytiv/rem#32]
If the input sample `l` is -32768, the calculated index becomes -2048 which will read out of  bounds and from another table leading to an incorrect returned value.

I have no clue how this works but noticed it when running your library with UBSAN.

https://github.com/creytiv/rem/blob/master/include/rem_g711.h#L49

```
static inline uint8_t g711_pcm2alaw(int16_t l)
{
	const uint8_t mask = (l < 0) ? 0x7f : 0xff;
	if (l < 0)
		l = -l;
	l >>= 4;

	return g711_l2A[l] & mask;
}
```

**Comment by alfredh** [comment]
a potential fix is to subtract 1 from l in case l is negative:

```c
	if (l < 0)
		l = -l - 1;
```

**Comment by richaas** [comment]
How about just adding one more entry to the end of the array?

**Comment by alfredh** [comment]
adding one more entry is a good idea, but the index is negative:

regular tests:       ../rem/include/rem_g711.h:49:17: runtime error: index -2048 out of bounds for type 'uint8_t [2049]'


`l = -l -1' is the same as `l = ~l' (compliment)

ref this code:

https://github.com/quatanium/foscam-ios-sdk/blob/master/g726lib/g711.c#L146

**Comment by richaas** [comment]
Yes, I see. OK, in that case -1 may be the best approach. This will however affect the returned result for many sample values, and needs to be properly tested. Is there some G.711 spec or reference implementation we can verify against?

**Comment by alfredh** [comment]
A suggested fix was posted here:

https://github.com/creytiv/rem/pull/33

**Comment by alfredh** [comment]
@kbeckmann can you please test again with commit c50937b960257d519e558f445a7a0893535b7bff

**Comment by kbeckmann** [comment]
I have tested with your patch and the issue seems to be fixed, thanks!

**Comment by alfredh** [comment]
Thanks for reporting the bug and verifying the fix!
