### ISSUE TITLE
vidconv scaling quality

### ISSUE THREAD

**Issue by perwx3** [creytiv/rem#34]
Hi Alfred and others,

I've noticed that vidconv outputs very 'jagged' results when scaling down. For example going from 1080p to 640x360. The output is worse than expected even though this is not interpolating at all from what i can see in the line handler, yuv420p_to_yuv420p. 

If I do a similiar downscale of an image in gimp using no interpolation, it seems to get better quality than vidconv. 

Is it possible that there is a bug somewhere in this code? Has anyone else noticed this?

I'm thinking of using swscale,, but i figure i should atleast ask the question. 

Br, 
Per

**Comment by alfredh** [comment]
the vidconv module in librem is a fast and basic module for
scaling and pixel-format conversion. it does not do any filtering,
and is just intended for very basic scaling, unless you know
what you are doing.

if you can manage to get a copy of the image that you converted,
you can upload it here so we can see it (both original and converted).

**Comment by perwx3** [comment]
I fiddled with this some more and compared vidconv with swscale filtered output in the same code and to my eyes it looks like vidconv is doing basically the same thing as SWS_POINT, which I'm guessing is 'no interpolation'. So there is probably no bug in vidconv, (sorry!) it just very basic as you say.

**Comment by alfredh** [comment]
vidconv is very basic yes.

if you need a high-quality scaler I can warmly recommend FFmpeg libswscale.
